#!/bin/sh

yum update -y
cp ./grafana.repo /etc/yum.repos.d/grafana.repo
yum install grafana -y

systemctl daemon-reload
systemctl start grafana-server
systemctl status grafana-server
systemctl enable grafana-server

cp ./ServiceNow-Optimiz-Plugins/grafana.ini /etc/grafana/grafana.ini
cp ./ServiceNow-Optimiz-Plugins/novatec-sdg-panel /var/lib/grafana/plugins/novatec-sdg-panel
cp ./ServiceNow-Optimiz-Plugins/servicenow-optimiz-plugin /var/lib/grafana/plugins/servicenow-optimiz-plugin

systemctl restart grafana-server
