#!/bin/sh

yum update -y
cp ./grafana.repo /etc/yum.repos.d/grafana.repo
yum install grafana -y

systemctl daemon-reload
systemctl start grafana-server
systemctl enable grafana-server

cp ./grafana.ini /etc/grafana/grafana.ini
cp -r ./novatec-sdg-panel /var/lib/grafana/plugins/novatec-sdg-panel
cp -r ./servicenow-optimiz-plugin /var/lib/grafana/plugins/servicenow-optimiz-plugin
cp ./dashboards/dashboards.yaml /etc/grafana/provisioning/dashboards/dashboards.yaml
cp -r ./dashboards /var/lib/grafana/dashboards

systemctl restart grafana-server

amazon-linux-extras install nginx1 -y

cp ./nginx.conf /etc/nginx/nginx.conf

systemctl enable nginx
systemctl restart nginx