{
 "title": "Application Service Details",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Application Service",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "allMetrics",
    "label": "Available Metrics",
    "query": {}
   },
   { "name": "childTopo", "label": "Child Topo Levels", "query": "0,1,2,3,4,5" },
   { "name": "parentTopo", "label": "Parent Topo Levels", "query": "0,1,2,3,4,5" },
   { "name": "namespaces" },
   {
    "name": "filterClasses",
    "query": {}
   },
   {
    "name": "nestedCIS",
    "query": {}
   },
   {
    "name": "relationshipType",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "$service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$service", "value": "$service" },
         "4": null
        }
       ],
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sortBy": { "description": "name", "label": "Name", "value": "name" },
       "sysparam_option1": [
        { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
        { "description": "busines_criticality", "label": "Business criticality", "value": "busines_criticality" },
        { "description": "severity", "label": "Severity", "value": "severity" },
        { "description": "type", "label": "Service Type", "value": "type" },
        { "description": "name", "label": "Name", "value": "name" },
        { "description": "u_business_segment.sys_id", "label": "Business Segment => Sys ID", "value": "u_business_segment.sys_id" }
       ],
       "sysparam_option2": [
        { "label": "is", "value": "=" },
        { "label": "is one of", "value": "IN" },
        { "label": "is one of", "value": "IN" },
        { "label": "is one of", "value": "IN" },
        { "label": "contains", "value": "LIKE" },
        { "description": "IN", "label": "is one of", "value": "IN" }
       ],
       "sysparam_option3": [
        { "label": "$service", "value": "$service" },
        { "label": "$business_criticality", "value": "$business_criticality" },
        { "label": "$severity", "value": "$severity" },
        { "label": "$type", "value": "$type" },
        { "label": "$nameSearch", "value": "$nameSearch" },
        { "label": "$businessSegment", "value": "$businessSegment" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" },
        { "label": "AND", "value": "^" },
        { "label": "AND", "value": "^" },
        { "label": "AND", "value": "^" },
        { "label": "AND", "value": "^" },
        { "label": "AND", "value": "^" }
       ],
       "tableName": { "description": "cmdb_ci_service_discovered", "label": "Mapped Application Service", "value": "cmdb_ci_service_discovered" }
      }
     ]
    },
    {
     "type": "state-timeline",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 4 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$service", "value": "$service" },
         "4": null
        }
       ],
       "selectedQueryCategory": {
        "description": "Gathers business service status over the last 90 days",
        "label": "Outage Status",
        "value": "Outage_Status"
       },
       "selectedServiceList": { "label": "$service", "value": "$service" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Topology",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
     "options": {
      "content": "<p><img src=\"/images/now-agent-icon.png\" width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Topology - <span style=\"font-size: 12pt; color: #eb459e;\">🏅 <em>click on the 'Child' and 'Parent' Topo Levels filters to expand view, also filter specific Relationship and CI Class!</em></span> &nbsp;</span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "type": "novatec-sdg-panel",
     "gridPos": { "h": 16, "w": 16, "x": 0, "y": 4 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$service", "value": "$service" },
         "4": null
        }
       ],
       "selectedQueryCategory": { "description": "Get Topology", "label": "Topology", "value": "Topology" },
       "selectedServiceList": { "label": "$service", "value": "$service" },
       "sysparam_query": "tionshipType^parent.sys_class_nameNOT IN$filterClasses^child.sys_class_nameNOT IN$filterClasses^parent.namespaceLIKE$namespace^child.namespaceLIKE$namespace",
       "topology_child_depth": "$childTopo",
       "topology_parent_depth": "$parentTopo"
      }
     ]
    }
   ]
  },
  { "title": "Active Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 3 },
   "options": {
    "content": "<p style=\"text-align: left;\"><span style=\"font-size: 14pt;\"><img src=\"/images/now-agent-icon.png\" width=\"27\" height=\"27\" alt=\"\" style=\"float: left;\" />&nbsp; Overall <span style=\"color: #f1c40f;\">Noise Reduction</span> Last 30 days</span></p>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 3 },
   "options": {
    "content": "<p style=\"text-align: center;\"><span style=\"font-size: 14pt;\"><img src=\"/images/now-agent-icon.png\" width=\"27\" height=\"27\" alt=\"\" />&nbsp; Active Alerts by <span style=\"color: #f1c40f;\">CI</span></span></p>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "event_count",
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$service", "value": "$service" },
       "4": null
      }
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "groupBy": "state",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedAggregateType": { "label": "SUM", "value": "SUM" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "service": "$service",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ciIN$ci",
     "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$service", "value": "$service" },
       "4": null
      }
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "service": "$service",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^group_source!=5^cmdb_ciIN$ci",
     "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "Incidents Last 30 Days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "service": "$service",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ciIN$ci",
     "tableName": { "label": "Incident (incident)", "value": "incident" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "panelId": 106,
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 9 },
   "options": {
    "content": "<p style=\"text-align: left;\"><span style=\"font-size: 14pt;\"><img src=\"/images/now-agent-icon.png\" width=\"27\" height=\"27\" alt=\"\" style=\"float: left;\" />&nbsp; Active Alerts <span style=\"font-size: 12pt; color: #eb459e;\">🏅<em>click on the 'group' link to drill into correlation insights!</em></span></span></p>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Alert Correlation Timeline",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Configuration item => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$ci", "value": "$ci" },
       "4": null
      }
     ],
     "selectedQueryCategory": {
      "description": "Get timeseries data based on a time trend",
      "label": "Trend Data",
      "value": "Trend_Data"
     },
     "selectedTrendBy": { "label": "Minute", "value": "minute" },
     "selectedTrendColumn": { "description": "sys_updated_on", "label": "Updated", "value": "sys_updated_on" },
     "sysparam_count": 1,
     "sysparam_option1": [
      { "description": "state", "label": "State", "value": "state" },
      { "description": "cmdb_ci.sys_id", "label": "Configuration item => Sys ID", "value": "cmdb_ci.sys_id" }
     ],
     "sysparam_option2": [
      { "description": "!=", "label": "is not", "value": "!=" },
      { "description": "IN", "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "Closed", "value": "Closed" },
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" },
     "trendPeriod": "2"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" },
       "4": null
      }
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedAlertTypeList": {
      "description": "Ignore CI selection and use sysparam_query",
      "label": "None",
      "value": "None"
     },
     "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
     "service": "$service",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "cmdb_ciIN$ci^sys_created_on>=javascript:gs.beginningOfLast30Days()"
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 28 },
     "options": {
      "content": "<p><img src=\"/images/now-agent-icon.png\" width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Metric Intelligence&nbsp; <span style=\"font-size: 10pt;\">*<em>select any metrics from '<strong>All Metrics</strong>' filter</em></span></span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "repeat": "allMetrics",
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": null,
         "2": null,
         "3": null,
         "4": null
        }
       ],
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": { "label": "$allMetrics", "value": "$allMetrics" },
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Recent Change Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 10, "x": 0, "y": 29 },
     "options": {
      "content": "<p><img src=\"/images/now-agent-icon.png\" width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Change Records - scope based on CI relationships&nbsp; </span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$service", "value": "$service" },
         "4": null
        }
       ],
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ciIN$ci"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$ci", "value": "$ci" },
         "4": null
        }
       ],
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "tableName": { "description": "sn_cmp_cloud_event", "label": "Cloud Event", "value": "sn_cmp_cloud_event" }
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$ci", "value": "$ci" },
         "4": null
        }
       ],
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}