{
 "title": "AWS CI Details",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "metric",
    "label": "KPI",
    "query": {}
   },
   {
    "name": "allMetrics",
    "query": {}
   },
   { "name": "childTopo", "label": "child_topo_levels", "query": "0,1,2,3,4,5" },
   { "name": "parentTopo", "label": "parent_topo_levels", "query": "0,1,2,3,4,5" },
   {
    "name": "filterClasses",
    "label": "Exclude Classes",
    "query": {}
   },
   {
    "name": "nestedCIS",
    "query": {}
   },
   { "name": "namespaces" }
  ]
 },
 "panels": [
  { "title": "$ci", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": {
      "description": "Get data from Database View tables",
      "label": "Database Views",
      "value": "Database_Views"
     },
     "service": "$service",
     "source": "$source",
     "sysparam_query": "vm_state=on^vm_sys_id=$ci",
     "tableColumns": "vm_last_discovered,ldc_name,ldc_object_id,ldc_region,vm_cpus,vm_disks,vm_disks_size,vm_guest_os_fullname,vm_ip_address,vm_last_discovered,vm_memory,vm_monitor,vm_name,vm_nics,vm_object_id,vm_state,vm_sys_id,vm_terminated_on,vm_vm_inst_id,vm_sys_class_name",
     "tableName": "sn_itom_pattern_amazon_vm_instance"
    }
   ]
  },
  { "title": "Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "novatec-sdg-panel",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Topology", "label": "Topology", "value": "Topology" },
     "selectedServiceList": {
      "__isNew__": true,
      "label": "$ci",
      "value": "$ci"
     },
     "service": "$service",
     "source": "$source",
     "topology_child_depth": "$childTopo",
     "topology_filter": "$filterClasses",
     "topology_parent_depth": "$parentTopo"
    }
   ]
  },
  {
   "title": "Tags",
   "type": "table",
   "gridPos": { "h": 13, "w": 10, "x": 13, "y": 5 },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get data from any table", "label": "Generic", "value": "Generic" },
     "service": "$service",
     "source": "$source",
     "sysparam_query": "configuration_item.sys_id=$ci",
     "tableName": "cmdb_key_value"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 19 },
   "options": {
    "content": "❗If the topology panel is returning an error or loading for a long time, you may be requesting too much data at once. <br/> Try adding more classes to the exclude list or lower your parent/child search levels to refine the search\n           "
   },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall Noise Reduction Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregateColumn": "event_count",
       "depends_on_toggle": "$dependsOnFilter",
       "groupBy": "state",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAggregateType": { "label": "SUM", "value": "SUM" },
       "selectedQueryCategory": {
        "description": "Group by and apply aggregate functions to table data",
        "label": "Aggregate",
        "value": "Aggregate"
       },
       "service": "$service",
       "source": "$source",
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS",
       "tableName": "em_alert"
      },
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^group_source!=5^cmdb_ci.sys_idIN$nestedCIS",
       "tableName": "em_alert"
      }
     ]
    },
    {
     "title": "Incidents Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS",
       "tableName": "incident"
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
       "selectedAlertTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
       "service": "$service",
       "sysparam_query": "cmdb_ci.sys_idIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cloud Events",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get data from any table", "label": "Generic", "value": "Generic" },
       "service": "$service",
       "source": "$source",
       "sysparam_query": "ci.sys_idIN$nestedCIS",
       "tableName": "sn_cmp_cloud_event"
      }
     ]
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "repeat": "allMetrics",
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": { "label": "$allMetrics", "value": "$allMetrics" },
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": { "label": "$ci", "value": "$ci" },
       "service": "$service",
       "source": "$ci"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 34 },
     "repeat": "metric",
     "targets": [
      {
       "metricAnomaly": "true",
       "metricName": "$metric",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "true", "value": "true" },
       "selectedMetricNameList": [
        {
         "__isNew__": true,
         "label": "$metric",
         "value": "$metric"
        }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        {
         "__isNew__": true,
         "label": "$ci",
         "value": "$ci"
        }
       ],
       "service": "$service",
       "source": "$ci"
      }
     ]
    }
   ]
  },
  {
   "title": "Change Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": { "description": "Get Changes at the CI level", "label": "CI", "value": "CI" },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": { "label": "$ci", "value": "$ci" },
       "service": "$service",
       "source": "$ci",
       "sysparam_query": "stateIN-2,-1,0,3^sys_created_on>=javascript:gs.beginningOfLast30Days()"
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": { "label": "$ci", "value": "$ci" },
       "service": "$service",
       "source": "$ci"
      }
     ]
    }
   ]
  }
 ]
}