{
 "title": "Compare Metrics",
 "tags": [
  "ACC",
  "Compare"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "metric",
    "label": "KPI",
    "query": {}
   },
   {
    "name": "allMetrics",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active ACC Agents",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "metricName": "/cpu|memory/",
     "metricType": "*",
     "selectedAgentFilter": {
      "__isNew__": true,
      "label": "$ci",
      "value": "$ci"
     },
     "selectedAgentFilterType": { "description": "Get all agents matching the CI", "label": "CI", "value": "CI" },
     "selectedMetricNameList": [
      {
       "__isNew__": true,
       "label": "cpu",
       "value": "cpu"
      },
      {
       "__isNew__": true,
       "label": "memory",
       "value": "memory"
      }
     ],
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": { "description": "Get Agent information", "label": "Agents", "value": "Agents" },
     "service": "$service",
     "sysparam_query": "state!=Closed"
    }
   ]
  },
  { "title": "Active Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedAlertTypeList": { "description": "Get Alerts at the CI level", "label": "CI", "value": "CI" },
     "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
     "selectedSourceList": [
      {
       "__isNew__": true,
       "label": "$ci",
       "value": "$ci"
      }
     ],
     "service": "$service",
     "source": "$ci"
    }
   ]
  },
  { "title": "All Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "$allMetrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "repeat": "allMetrics",
   "targets": [
    {
     "metricAnomaly": "false",
     "metricName": "$allMetrics",
     "metricType": "*",
     "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
     "selectedMetricNameList": [
      {
       "__isNew__": true,
       "label": "$allMetrics",
       "value": "$allMetrics"
      }
     ],
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "selectedServiceList": {
      "__isNew__": true,
      "label": "$service",
      "value": "$service"
     },
     "selectedSourceList": [
      {
       "__isNew__": true,
       "label": "$ci",
       "value": "$ci"
      }
     ],
     "service": "$service",
     "source": "$ci"
    }
   ]
  },
  {
   "title": "Change Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": { "description": "Get Changes at the CI level", "label": "CI", "value": "CI" },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        {
         "__isNew__": true,
         "label": "$ci",
         "value": "$ci"
        }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_query": "stateIN-2,-1,0,3^sys_created_on>=javascript:gs.beginningOfLast30Days()"
      }
     ]
    }
   ]
  },
  {
   "title": "$ci - Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "ci",
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        {
         "__isNew__": true,
         "label": "$ci",
         "value": "$ci"
        }
       ],
       "service": "$service",
       "source": "$ci"
      }
     ]
    }
   ]
  }
 ]
}