{
 "title": "Kubernetes Details",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "metric",
    "label": "Metric KPI",
    "query": {}
   },
   {
    "name": "allMetrics",
    "label": "All Metrics",
    "query": {}
   },
   { "name": "childTopo", "label": "Child Topo Levels", "query": "0,1,2,3,4,5" },
   { "name": "parentTopo", "label": "Parent Topo Levels", "query": "0,1,2,3,4,5" },
   { "name": "namespaces" },
   {
    "name": "filterClasses",
    "label": "Exclude Classes",
    "query": {}
   },
   {
    "name": "nestedCIS",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$ci", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get data from any table", "label": "Generic", "value": "Generic" },
     "service": "$service",
     "source": "$source",
     "sysparam_query": "operational_status=1^sys_id=$ci",
     "tableColumns": "resource_function_last_modified,resource_name,resource_operational_status,resource_object_id,resource_sys_class_name,resource_language,resource_used_for,resource_function_state,resource_is_clustered,resource_sys_id,resource_aws_resource_name,resource_last_discovered,resource_code_location_url",
     "tableName": "cmdb_ci_kubernetes_service"
    },
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get data from any table", "label": "Generic", "value": "Generic" },
     "service": "$service",
     "source": "$source",
     "sysparam_query": "operational_status=1^sys_id=$ci",
     "tableName": "cmdb_ci_kubernetes_pod"
    },
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get data from any table", "label": "Generic", "value": "Generic" },
     "service": "$service",
     "source": "$source",
     "sysparam_query": "operational_status=1^sys_id=$ci",
     "tableName": "cmdb_ci_kubernetes_deployment"
    }
   ]
  },
  { "title": "Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "novatec-sdg-panel",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 6 },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Topology", "label": "Topology", "value": "Topology" },
     "selectedServiceList": {
      "__isNew__": true,
      "label": "$ci",
      "value": "$ci"
     },
     "service": "$service",
     "source": "$source",
     "topology_child_depth": "$childTopo",
     "topology_filter": "$filterClasses",
     "topology_namespaces": "$namespaces",
     "topology_parent_depth": "$parentTopo"
    }
   ]
  },
  {
   "title": "Tags",
   "type": "table",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get data from any table", "label": "Generic", "value": "Generic" },
     "service": "$service",
     "source": "$source",
     "sysparam_query": "configuration_item.sys_id=$ci",
     "tableName": "cmdb_key_value"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 20 },
   "options": {
    "content": "❗If the topology panel is returning an error or loading for a long time, you may be requesting too much data at once. <br/> Try adding more classes to the exclude list or lower your parent/child search levels to refine the search\n           "
   },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  { "title": "Active Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "ITOM Alerts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedAlertTypeList": { "description": "Get Alerts at the CI level", "label": "CI", "value": "CI" },
     "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
     "selectedSourceList": { "label": "$nestedCIS", "value": "$nestedCIS" },
     "service": "$service",
     "source": "$nestedCIS"
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
     "repeat": "allMetrics",
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": { "label": "$allMetrics", "value": "$allMetrics" },
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": { "label": "$ci", "value": "$ci" },
       "service": "$service",
       "source": "$ci"
      }
     ]
    }
   ]
  },
  {
   "title": "Change/Deployment Records & Cloud Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cloud Events",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get data from any table", "label": "Generic", "value": "Generic" },
       "service": "$service",
       "source": "$source",
       "sysparam_query": "ci.sys_idIN$nestedCIS",
       "tableName": "sn_cmp_cloud_event"
      }
     ]
    },
    {
     "title": "Change/Deployment Records",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": { "description": "Get Changes at the CI level", "label": "CI", "value": "CI" },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": { "label": "$ci", "value": "$ci" },
       "service": "$service",
       "source": "$ci",
       "sysparam_query": "stateIN-2,-1,0,3^sys_created_on>=javascript:gs.beginningOfLast30Days()"
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": { "label": "$ci", "value": "$ci" },
       "service": "$service",
       "source": "$ci"
      }
     ]
    }
   ]
  }
 ]
}