{
 "title": "vCenter CI Details",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "metric",
    "label": "KPI",
    "query": {}
   },
   {
    "name": "allMetrics",
    "query": {}
   },
   { "name": "childTopo", "label": "child_topo_levels", "query": "0,1,2,3,4,5" },
   { "name": "parentTopo", "label": "parent_topo_levels", "query": "0,1,2,3,4,5" },
   {
    "name": "filterClasses",
    "label": "Exclude Classes",
    "query": {}
   },
   {
    "name": "nestedCIS",
    "query": {}
   },
   {
    "name": "relationshipType",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$ci", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "cpus", "label": "CPUs", "value": "cpus" },
      { "description": "discovery_source", "label": "Discovery source", "value": "discovery_source" },
      { "description": "disks", "label": "Disks", "value": "disks" },
      { "description": "disks_size", "label": "Disks size (GB)", "value": "disks_size" },
      { "description": "first_discovered", "label": "First discovered", "value": "first_discovered" },
      { "description": "fqdn", "label": "Fully qualified domain name", "value": "fqdn" },
      { "description": "guest_id", "label": "Guest ID", "value": "guest_id" },
      { "description": "guest_os_fullname", "label": "Guest OS Name", "value": "guest_os_fullname" },
      { "description": "image_path", "label": "Image path", "value": "image_path" },
      { "description": "install_status", "label": "Status", "value": "install_status" },
      { "description": "ip_address", "label": "IP Address", "value": "ip_address" },
      { "description": "last_discovered", "label": "Most recent discovery", "value": "last_discovered" },
      { "description": "memory", "label": "Memory (MB)", "value": "memory" },
      { "description": "name", "label": "Name", "value": "name" },
      { "description": "nics", "label": "Network adapters", "value": "nics" },
      { "description": "object_id", "label": "Object ID", "value": "object_id" },
      { "description": "operational_status", "label": "Operational status", "value": "operational_status" },
      { "description": "state", "label": "State", "value": "state" },
      { "description": "sys_class_name", "label": "Class", "value": "sys_class_name" },
      { "description": "sys_created_on", "label": "Created", "value": "sys_created_on" },
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
      { "description": "sys_updated_on", "label": "Updated", "value": "sys_updated_on" },
      { "description": "terminated_on", "label": "Terminated On", "value": "terminated_on" },
      { "description": "vcenter_ref.name", "label": "vCenter Reference => Name", "value": "vcenter_ref.name" },
      { "description": "vm_cluster_name", "label": "VM Cluster name", "value": "vm_cluster_name" },
      { "description": "vm_instance_uuid", "label": "VM Instance UUID", "value": "vm_instance_uuid" }
     ],
     "sysparam_count": 1,
     "sysparam_option1": [
      { "description": "state", "label": "State", "value": "state" },
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" }
     ],
     "sysparam_option2": [
      { "description": "=", "label": "is", "value": "=" },
      { "description": "=", "label": "is", "value": "=" }
     ],
     "sysparam_option3": [
      { "label": "on", "value": "on" },
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": {
      "description": "cmdb_ci_vmware_instance",
      "label": "VMware Virtual Machine Instance",
      "value": "cmdb_ci_vmware_instance"
     }
    },
    {
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "vmware_vm_instance.sys_id", "label": "VMware VM instance => Sys ID", "value": "vmware_vm_instance.sys_id" },
      { "label": "datacenter", "value": "datacenter" }
     ],
     "sysparam_count": 1,
     "sysparam_option1": [
      { "description": "vmware_vm_instance.state", "label": "VMware VM instance => State", "value": "vmware_vm_instance.state" },
      { "description": "vmware_vm_instance.sys_id", "label": "VMware VM instance => Sys ID", "value": "vmware_vm_instance.sys_id" },
      { "label": "vm_name", "value": "vm_name" }
     ],
     "sysparam_option2": [
      { "description": "=", "label": "is", "value": "=" },
      { "description": "=", "label": "is", "value": "=" },
      { "description": "LIKE", "label": "contains", "value": "LIKE" }
     ],
     "sysparam_option3": [
      { "label": "on", "value": "on" },
      { "label": "$ci", "value": "$ci" },
      { "label": "$nameSearch", "value": "$nameSearch" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": {
      "description": "sn_disco_cd_vmware_vm_analytics",
      "label": "VMware VM Analytics",
      "value": "sn_disco_cd_vmware_vm_analytics"
     }
    },
    {
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "label": "ci_sys_id", "value": "ci_sys_id" },
      { "label": "massoc_environment", "value": "massoc_environment" }
     ],
     "sysparam_option1": [
      { "label": "ci_sys_class_name", "value": "ci_sys_class_name" }
     ],
     "sysparam_option2": [
      { "description": "=", "label": "is", "value": "=" }
     ],
     "sysparam_option3": [
      { "label": "cmdb_ci_vmware_instance", "value": "cmdb_ci_vmware_instance" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "tableName": { "label": "sa_service_list_view", "value": "sa_service_list_view" }
    }
   ]
  },
  { "title": "Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "novatec-sdg-panel",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Topology", "label": "Topology", "value": "Topology" },
     "selectedServiceList": {
      "__isNew__": true,
      "label": "$ci",
      "value": "$ci"
     },
     "service": "$service",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "typeIN$relationshipType^parent.sys_class_nameNOT IN$filterClasses^child.sys_class_nameNOT IN$filterClasses",
     "topology_child_depth": "$childTopo",
     "topology_filter": "$filterClasses",
     "topology_parent_depth": "$parentTopo"
    }
   ]
  },
  {
   "title": "Tags",
   "type": "table",
   "gridPos": { "h": 13, "w": 10, "x": 13, "y": 5 },
   "targets": [
    {
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "label": "tags_key", "value": "tags_key" },
      { "label": "tags_value", "value": "tags_value" },
      { "label": "vmwarevm_vmware_vm_instance", "value": "vmwarevm_vmware_vm_instance" }
     ],
     "sysparam_option1": [
      { "label": "vmwarevm_vmware_vm_instance", "value": "vmwarevm_vmware_vm_instance" }
     ],
     "sysparam_option2": [
      { "description": "=", "label": "is", "value": "=" }
     ],
     "sysparam_option3": [
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "tableName": {
      "label": "sn_disco_cd_vmware_vm_analytics_tags_db_view",
      "value": "sn_disco_cd_vmware_vm_analytics_tags_db_view"
     }
    }
   ]
  },
  { "title": "Change Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedChangeTypeList": {
      "description": "Ignore CI selection and use sysparam_query",
      "label": "None",
      "value": "None"
     },
     "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
     "service": "$service",
     "source": "$ci",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "cmdb_ciIN$nestedCIS"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall Noise Reduction Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregateColumn": "event_count",
       "depends_on_toggle": "$dependsOnFilter",
       "groupBy": "state",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAggregateType": { "label": "SUM", "value": "SUM" },
       "selectedQueryCategory": {
        "description": "Group by and apply aggregate functions to table data",
        "label": "Aggregate",
        "value": "Aggregate"
       },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS^state!=Closed",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
      },
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^group_source!=5^cmdb_ci.sys_idIN$nestedCIS^state!=Closed",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
      }
     ]
    },
    {
     "title": "Incidents Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS",
       "tableName": { "label": "Incident (incident)", "value": "incident" }
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
       "selectedAlertTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
       "service": "$service",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ci.sys_idIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "vCenter Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sysparam_option1": [
        { "description": "instance", "label": "Instance", "value": "instance" }
       ],
       "sysparam_option2": [
        { "description": "IN", "label": "is one of", "value": "IN" }
       ],
       "sysparam_option3": [
        { "label": "$nestedCIS", "value": "$nestedCIS" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "sysevent", "label": "Event", "value": "sysevent" }
      }
     ]
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
     "repeat": "allMetrics",
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": { "label": "$allMetrics", "value": "$allMetrics" },
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "$metric",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 27 },
     "repeat": "metric",
     "targets": [
      {
       "metricAnomaly": "true",
       "metricName": "$metric",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "true", "value": "true" },
       "selectedMetricNameList": [
        {
         "__isNew__": true,
         "label": "$metric",
         "value": "$metric"
        }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}