{
 "title": "Compare CIs",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "query": {}
   },
   {
    "name": "ci",
    "label": "Hosts",
    "query": {}
   },
   {
    "name": "allMetrics",
    "label": "All Metrics",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<p><img src=\"/images/now-agent-icon.png\" width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Select multiple <span style=\"color: #2dc26b;\">Hosts</span> from filter ☝<span style=\"font-size: 10pt;\"></span></span></p>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  { "title": "Compare CIs:  $ci", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Host Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$ci", "value": "$ci" },
       "4": null
      }
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "/cpu|memory/",
     "metricType": "*",
     "selectedAgentFilter": {
      "__isNew__": true,
      "label": "$ciClasses",
      "value": "$ciClasses"
     },
     "selectedAgentFilterType": { "description": "Get all agents matching the OS", "label": "OS", "value": "OS" },
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "name", "label": "Name", "value": "name" },
      { "description": "status", "label": "Status", "value": "status" },
      { "description": "cmdb_ci.name", "label": "Host => Name", "value": "cmdb_ci.name" },
      { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
      { "description": "cmdb_ci.sys_class_name", "label": "Host => Class", "value": "cmdb_ci.sys_class_name" },
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
      { "description": "running_checks_num", "label": "Number of running checks", "value": "running_checks_num" },
      { "description": "data_collection", "label": "Data Collection", "value": "data_collection" },
      { "description": "agent_version", "label": "Version", "value": "agent_version" },
      { "description": "ip_address", "label": "IP address", "value": "ip_address" },
      { "description": "cmdb_ci.last_discovered", "label": "Host => Most recent discovery", "value": "cmdb_ci.last_discovered" },
      {
       "description": "cmdb_ci.fqdn",
       "label": "Host => Fully qualified domain name",
       "value": "cmdb_ci.fqdn"
      },
      { "label": "cmdb_ci.os", "value": "cmdb_ci.os" },
      { "description": "mid.name", "label": "Mid => Name", "value": "mid.name" },
      { "description": "cmdb_ci.location", "label": "Host => Location", "value": "cmdb_ci.location" },
      { "description": "cmdb_ci.environment", "label": "Host => Environment", "value": "cmdb_ci.environment" },
      { "description": "cmdb_ci.u_critical", "label": "Host => Critical", "value": "cmdb_ci.u_critical" },
      { "description": "cmdb_ci.model_id", "label": "Host => Model ID", "value": "cmdb_ci.model_id" },
      { "description": "cmdb_ci.support_group", "label": "Host => Support group", "value": "cmdb_ci.support_group" }
     ],
     "service": "$service",
     "sysparam_option1": [
      { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
      { "description": "mid.sys_id", "label": "Mid => Sys ID", "value": "mid.sys_id" },
      { "description": "cmdb_ci.name", "label": "Host => Name", "value": "cmdb_ci.name" },
      { "description": "cmdb_ci.location", "label": "Host => Location", "value": "cmdb_ci.location" },
      { "description": "cmdb_ci.environment", "label": "Host => Environment", "value": "cmdb_ci.environment" }
     ],
     "sysparam_option2": [
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "LIKE", "label": "contains", "value": "LIKE" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "$ci", "value": "$ci" },
      { "label": "$mid", "value": "$mid" },
      { "label": "$hostSearch", "value": "$hostSearch" },
      { "label": "$location", "value": "$location" },
      { "label": "$usedFor", "value": "$usedFor" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" }
     ],
     "sysparam_query": "agent_extended_info.status!=2^mid.name=MID1_PROD_ATL0WSNWP022",
     "tableName": { "description": "sn_agent_ci_extended_info", "label": "Agent Client Collector Info", "value": "sn_agent_ci_extended_info" }
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 12 },
     "options": {
      "content": "<p><img src=\"/images/now-agent-icon.png\" width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">ITOM Alerts <span style=\"color: #2dc26b;\"></span><span style=\"font-size: 10pt;\"></span></span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$ci", "value": "$ci" },
         "4": null
        }
       ],
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
       "selectedAlertTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
       "service": "$service",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ciIN$ci"
      }
     ]
    }
   ]
  },
  { "title": "All Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 13 },
   "options": {
    "content": "<p><img src=\"/images/now-agent-icon.png\" width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Metric Intelligence&nbsp; <span style=\"font-size: 10pt;\">*<em>select any metrics from '<strong>All Metrics</strong>' filter</em></span></span></p>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "title": "$allMetrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "repeat": "allMetrics",
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$ci", "value": "$ci" },
       "4": null
      }
     ],
     "metricAnomaly": "false",
     "metricName": "$allMetrics",
     "metricType": "*",
     "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
     "selectedMetricNameList": { "label": "$allMetrics", "value": "$allMetrics" },
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "selectedSourceList": [
      { "label": "$ci", "value": "$ci" }
     ],
     "service": "$service",
     "source": "$ci",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Change Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 10, "x": 0, "y": 24 },
     "options": {
      "content": "<p><img src=\"/images/now-agent-icon.png\" width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Change Records&nbsp; </span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "Change Records",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$ci", "value": "$ci" },
         "4": null
        }
       ],
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ciIN$ci^sys_created_on>=javascript:gs.beginningOfLast30Days()"
      }
     ]
    }
   ]
  }
 ]
}