{
 "title": "Observability Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "k8_cluster",
    "label": "Cluster",
    "query": {}
   },
   {
    "name": "k8_node",
    "label": "Node",
    "query": {}
   },
   {
    "name": "k8_node_metrics",
    "label": "Node KPI Metrics",
    "query": {}
   },
   {
    "name": "k8_service",
    "label": "Svc",
    "query": {}
   },
   {
    "name": "allMetrics",
    "label": "Svc Metrics",
    "query": {}
   },
   {
    "name": "metric",
    "label": "Svc KPI Metrics",
    "query": {}
   },
   { "name": "childTopo", "label": "Child Topo Levels", "query": "0,1,2,3,4,5,6" },
   { "name": "parentTopo", "label": "Parent Topo Levels", "query": "0,1,2,3,4,5,6" },
   { "name": "namespaces" },
   {
    "name": "nestedCIS",
    "query": {}
   },
   {
    "name": "service",
    "query": {}
   },
   {
    "name": "serviceName",
    "query": {}
   },
   {
    "name": "configFile",
    "query": {}
   },
   {
    "name": "filterClasses",
    "label": "Exclude Classes",
    "query": {}
   },
   {
    "name": "relationshipType",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "sysparam_option1": [
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" }
     ],
     "sysparam_option2": [
      { "description": "=", "label": "is", "value": "=" }
     ],
     "sysparam_option3": [
      { "label": "$service", "value": "$service" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "tableName": { "description": "cmdb_ci_service_discovered", "label": "Mapped Application Service", "value": "cmdb_ci_service_discovered" }
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "selectedQueryCategory": {
      "description": "Gathers business service status over the last 90 days",
      "label": "Outage Status",
      "value": "Outage_Status"
     },
     "selectedServiceList": { "label": "$service", "value": "$service" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "options": {
    "content": "<br/>\n<br/>\n<div style=\"position: absolute; bottom: 0\">\n  <a href=\"https://itomvision2demo.service-now.com/now/workspace/agent/log_viewer\" target=\"_blank\" style=\"font-size: 20px; text-decoration: none; color: inherit\"><img src=\"https://regoconsulting.com/wp-content/uploads/2019/03/RegoLink-integration-icons-01.png\" style=\"height: 50px\">   Cloud Native</a>\n</div>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Global Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"source\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", response_code=~\"5.*\"}[1m]))"
    }
   ]
  },
  {
   "type": "novatec-sdg-panel",
   "gridPos": { "h": 15, "w": 13, "x": 0, "y": 11 },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Topology", "label": "Topology", "value": "Topology" },
     "selectedServiceList": { "label": "$service", "value": "$service" },
     "selectedTopologyDependsOnFilter": { "label": "$dependsOnFilter", "value": "$dependsOnFilter" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "typeIN$relationshipType^parent.sys_class_nameNOT IN$filterClasses^child.sys_class_nameNOT IN$filterClasses^parent.namespaceLIKE$namespace^child.namespaceLIKE$namespace",
     "topology_child_depth": "$childTopo",
     "topology_filter": "$filterClasses",
     "topology_namespaces": "$namespaces",
     "topology_parent_depth": "$parentTopo"
    }
   ]
  },
  {
   "title": "[ $k8_node ] $k8_node_metrics",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 11 },
   "repeat": "k8_node_metrics",
   "targets": [
    {
     "metricAnomaly": "true",
     "metricName": "$metric",
     "metricType": "*",
     "selectedMetricAnomalyList": { "label": "false", "value": "false" },
     "selectedMetricNameList": { "label": "$k8_node_metrics", "value": "$k8_node_metrics" },
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "selectedSourceList": [
      { "label": "$k8_node", "value": "$k8_node" }
     ],
     "service": "$service",
     "source": "$ci",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "title": "ITOM Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
       "selectedAlertTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
       "service": "$service",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ci.sys_idIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "K8s Service Metrics - $k8_service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "$metric",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
     "repeat": "metric",
     "targets": [
      {
       "metricAnomaly": "true",
       "metricName": "$metric",
       "metricType": "*",
       "selectedMetricAnomalyList": { "label": "true", "value": "true" },
       "selectedMetricNameList": { "label": "$metric", "value": "$metric" },
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedSourceList": [
        { "label": "$k8_service", "value": "$k8_service" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Config File",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "$configFile",
     "type": "text",
     "gridPos": { "h": 13, "w": 13, "x": 0, "y": 27 },
     "options": {
      "content": "<pre>\r\n  $configFile\r\n</pre>"
     },
     "targets": [
      {
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "selectedtableColumns": [
        { "description": "related_ci.name", "label": "Related CI => Name", "value": "related_ci.name" },
        { "description": "content", "label": "File Content", "value": "content" },
        { "description": "name", "label": "File Name", "value": "name" }
       ],
       "sysparam_option1": [
        { "description": "related_ci.sys_id", "label": "Related CI => Sys ID", "value": "related_ci.sys_id" }
       ],
       "sysparam_option2": [
        { "description": "=", "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$k8_service", "value": "$k8_service" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_ci_config_file_tracked", "label": "Tracked Configuration file", "value": "cmdb_ci_config_file_tracked" }
      }
     ]
    }
   ]
  },
  {
   "title": "Metric Summaries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "$k8_node",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedSourceList": [
        { "label": "$k8_node", "value": "$k8_node" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "$k8_service",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedSourceList": [
        { "label": "$k8_service", "value": "$k8_service" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}